### ISSUE TITLE
Crash with liquid in GUI (or invisible items w/ optifine)

### ISSUE THREAD

**Issue by JWTHDYTWA** [codetaylor/artisan-worktables#52]
Artisan Worktables version: 1.11.21
Athenaeum version: 1.6.4

Without fluid:
![Without](https://i.imgur.com/Bqn6Sk1.png)

With fluid:
![With](https://i.imgur.com/c1SpuGO.png)

No crashlog because there is no crash...

**Comment by JWTHDYTWA** [comment]
By the way, it is 200+ mods on this modpack, including optifine and some other.

**Comment by JWTHDYTWA** [comment]
It is just visual bug, so i can perform craft... to the touch.

**Comment by codetaylor** [comment]
If you remove or disable optifine, does the bug persist?

**Comment by codetaylor** [comment]
Does it happen only when moving the mouse over the liquid tank display?

**Comment by JWTHDYTWA** [comment]
> If you remove or disable optifine, does the bug persist?

Ehm... i tried to test it with removed optifine, but this time game entirely crashed... so here's fresh crashlog:
https://gist.github.com/Warrock3280/7b23c4cf9f357ca45de8ab49c7b1c8df

> Does it happen only when moving the mouse over the liquid tank display?

No, everything but JEI interface and solid GUI isn't render at all just if liquid is present. Thus item icons, backlight of selected slot, item tips, liquid bar and even worktable title isn't render.

**Comment by Remyrios** [comment]
I hope this gets fixed fast because i'm unable to use the tables and i need them for like 35% recipes

**Comment by codetaylor** [comment]
@Warrock3280 Thank you for testing without optifine and providing a crash log. This is helpful.

@Kaperios The information that you provided doesn't help me solve the issue. I would like to be able to fix this issue quickly. If you would like to help, you can provide:
* a link to your crash log (don't copy and paste the log here)
* versions of relevant mods and forge
* any contextual information about how to reproduce the bug:
  * what were you doing
  * when does it occur
  * are you using optifine
* any other information you think is relevant to this issue

**Comment by codetaylor** [comment]
I was unable to reproduce this issue in dev, but was able to reproduce it by downloading the latest betas from curse and spinning up a new instance. I then decompiled the downloaded files and found a discrepancy.

```
GuiHelper.drawVerticalScaledTexturedModalRectFromIconAnchorBottomLeft(this.field_147003_i + 8, 
      
        GuiHelper.getFluidY(tank
        .getFluidAmount(), tank
        .getCapacity(), 52, (this.field_146295_m - this.field_147000_g) / 2 + 17), 0.0F, this.fluidSprite, 6, 
        
        GuiHelper.getFluidHeight(tank.getFluidAmount(), tank.getCapacity(), 52));
```

This clearly doesn't match the lib's method signature (3rd parameter):

```
public static void drawVerticalScaledTexturedModalRectFromIconAnchorBottomLeft(
      int x,
      int y,
      int z,
      TextureAtlasSprite icon,
      int width,
      int height
  )
```

The only thing that I think could have caused this is a desynced gradle build artifact left over from switching branches, making edits, and forgetting to `clean` before `build`.

I am confident that this is resolved in the new ~~beta~~ alpha builds. Expect the new ~~beta~~ alpha builds of the lib and mod within 24 hours.

**Comment by codetaylor** [comment]
In the meantime, I rebuilt 1.12.2-1.11.21 and confirmed that it does not have this issue.

You can find the rebuild here: https://github.com/codetaylor/artisan-worktables/releases/tag/1.11.21

**Comment by Xaikii** [comment]
In case this error is not fixed, you should try without the mod "foamfix" it is known to have some issues with rendering

**Comment by JWTHDYTWA** [comment]
@Xaikii 
It's ok, problem solved in this patch:

> You can find the rebuild here: https://github.com/codetaylor/artisan-worktables/releases/tag/1.11.21

**Comment by codetaylor** [comment]
Should no longer be a problem with the new alpha 1.12.2-1.12.21

https://minecraft.curseforge.com/projects/artisan-worktables/files/2528402
